name: signed

on: 
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      # Repository
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 10

      # History
      - name: List git history (for debugging purposes)
        run: git log --oneline -n 10

      # Environment
      - name: Download environment files
        run: |
          wget https://raw.githubusercontent.com/Auto-Mech/amech-dev/main/pyproject.toml -P ..
          wget https://raw.githubusercontent.com/Auto-Mech/amech-dev/main/pixi.lock -P ..
          mkdir -p ../src/automech
          touch ../src/automech/__init__.py

      - name: Set up Pixi
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          manifest-path: ../pyproject.toml

      - name: Pip install
        run: |
          pixi run pip install git+https://github.com/Auto-Mech/autochem.git --no-deps
          pixi run pip install git+https://github.com/Auto-Mech/autoio.git --no-deps
          pixi run pip install git+https://github.com/Auto-Mech/autofile.git --no-deps
          pixi run pip install git+https://github.com/Auto-Mech/mechanalyzer.git --no-deps
          pixi run pip install -e . --no-deps

      # Test
      - name: Test
        run: |
          pixi run pytest -v tests/ -k "signature"
